const RECORD_ADDRESS = "RECORD_ADDRESS";
const SAVE_GEOHASH = "SAVE_GEOHASH";
const ADD_CART = "ADD_CART";
const REDUCE_CART = "REDUCE_CART";
const INIT_BUYCART = "INIT_BUYCART";
const CLEAR_CART = "CLEAR_CART";
export {
  RECORD_ADDRESS,
  SAVE_GEOHASH,
  ADD_CART,
  INIT_BUYCART,
  CLEAR_CART,
  REDUCE_CART,
};
